"""empty message

Revision ID: 0369175f1dcc
Revises: 1d5e06d68205
Create Date: 2022-09-14 18:34:06.693917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0369175f1dcc'
down_revision = '1d5e06d68205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizacion', 'phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=9),
               existing_nullable=False)
    op.alter_column('organizacion', 'instagram',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizacion', 'instagram',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('organizacion', 'phone',
               existing_type=sa.String(length=9),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
