"""empty message

Revision ID: 09973922a224
Revises: b339858ebcfc
Create Date: 2022-10-21 21:26:14.276987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09973922a224'
down_revision = 'b339858ebcfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pets_name_key', 'pets', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pets_name_key', 'pets', ['name'])
    # ### end Alembic commands ###
