"""empty message

Revision ID: 0a388d0941f7
Revises: 7aab18eaed61
Create Date: 2022-09-14 10:49:02.568125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a388d0941f7'
down_revision = '7aab18eaed61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('years', sa.String(length=120), nullable=False))
    op.drop_constraint('pets_yearsofbirth_key', 'pets', type_='unique')
    op.create_unique_constraint(None, 'pets', ['years'])
    op.drop_column('pets', 'yearsofbirth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('yearsofbirth', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pets', type_='unique')
    op.create_unique_constraint('pets_yearsofbirth_key', 'pets', ['yearsofbirth'])
    op.drop_column('pets', 'years')
    # ### end Alembic commands ###
