"""empty message

Revision ID: 213208307d20
Revises: 6127d213e6cf
Create Date: 2022-09-05 18:07:44.188129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213208307d20'
down_revision = '6127d213e6cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizacion', sa.Column('avaiability', sa.Integer(), nullable=True))
    op.add_column('organizacion', sa.Column('animals', sa.Integer(), nullable=True))
    op.alter_column('organizacion', 'phone',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizacion', 'phone',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('organizacion', 'animals')
    op.drop_column('organizacion', 'avaiability')
    # ### end Alembic commands ###
