"""empty message

Revision ID: 26ff329ada3d
Revises: ad49a6e47bcf
Create Date: 2022-10-04 20:16:59.410734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ff329ada3d'
down_revision = 'ad49a6e47bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pets_years_key', 'pets', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pets_years_key', 'pets', ['years'])
    # ### end Alembic commands ###
