"""empty message

Revision ID: 6127d213e6cf
Revises: c9bcf234b5c5
Create Date: 2022-09-05 17:53:48.095733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6127d213e6cf'
down_revision = 'c9bcf234b5c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protectora')
    op.drop_table('acogida')
    op.add_column('pets', sa.Column('organizacion_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pets', 'organizacion', ['organizacion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.drop_column('pets', 'organizacion_id')
    op.create_table('acogida',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pets_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organizacion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizacion.id'], name='acogida_organizacion_id_fkey'),
    sa.ForeignKeyConstraint(['pets_id'], ['pets.id'], name='acogida_pets_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='acogida_pkey')
    )
    op.create_table('protectora',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pets_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organizacion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizacion.id'], name='protectora_organizacion_id_fkey'),
    sa.ForeignKeyConstraint(['pets_id'], ['pets.id'], name='protectora_pets_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='protectora_pkey')
    )
    # ### end Alembic commands ###
