"""empty message

Revision ID: 85e08420ca5c
Revises: 26ff329ada3d
Create Date: 2022-10-04 20:19:23.807816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e08420ca5c'
down_revision = '26ff329ada3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pets_convivencia_key', 'pets', type_='unique')
    op.drop_constraint('pets_race_key', 'pets', type_='unique')
    op.drop_constraint('pets_sexo_key', 'pets', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pets_sexo_key', 'pets', ['sexo'])
    op.create_unique_constraint('pets_race_key', 'pets', ['race'])
    op.create_unique_constraint('pets_convivencia_key', 'pets', ['convivencia'])
    # ### end Alembic commands ###
