"""empty message

Revision ID: b3de068b3bb9
Revises: 2fb59b739bb3
Create Date: 2022-09-05 18:16:03.215572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3de068b3bb9'
down_revision = '2fb59b739bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizacion', sa.Column('city', sa.String(length=80), nullable=False))
    op.drop_column('organizacion', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizacion', sa.Column('address', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('organizacion', 'city')
    # ### end Alembic commands ###
