"""empty message

Revision ID: e278645b866e
Revises: 0a388d0941f7
Create Date: 2022-09-14 10:49:56.161338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e278645b866e'
down_revision = '0a388d0941f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('convivencia', sa.String(length=120), nullable=False))
    op.add_column('pets', sa.Column('Sexo', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'pets', ['Sexo'])
    op.create_unique_constraint(None, 'pets', ['convivencia'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pets', type_='unique')
    op.drop_constraint(None, 'pets', type_='unique')
    op.drop_column('pets', 'Sexo')
    op.drop_column('pets', 'convivencia')
    # ### end Alembic commands ###
