"""empty message

Revision ID: ff99c61df5f9
Revises: 
Create Date: 2022-10-05 18:20:50.145900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff99c61df5f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=9), nullable=False),
    sa.Column('instagram', sa.String(length=80), nullable=True),
    sa.Column('avaiability', sa.String(length=30), nullable=True),
    sa.Column('animals', sa.String(length=30), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('instagram')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('years', sa.String(length=120), nullable=False),
    sa.Column('convivencia', sa.String(length=120), nullable=False),
    sa.Column('sexo', sa.String(length=120), nullable=False),
    sa.Column('photo', sa.String(length=250), nullable=True),
    sa.Column('race', sa.String(length=120), nullable=False),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('convivencia'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('race'),
    sa.UniqueConstraint('sexo'),
    sa.UniqueConstraint('years')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    op.drop_table('organizacion')
    op.drop_table('rol')
    # ### end Alembic commands ###
